REFACTOR: 테스트 DB 설정, 음식점 정보 수정 테스트
f-lab-edu/food-reservation pull request #15
Opened 2022-07-24 08:35 UTC by SOULIKK

Address 클래스에 StoreUpdateDto 참조되는 부분 제거했습니다.
수정된 음식점의 id값을 리턴하도록 수정했습니다.
StoreUpdateDto의 클래스명을 UpdateStoreRequest로 수정했습니다.
UpdateStoreRequest에서 Seller 객체가 아닌 sellerId를 받도록 수정했습니다.
@SpringBootTest를 포함한 Repositoty 테스트에서 Mockito를 사용한 유닛테스트로 수정하였습니다.

2022-07-25 10:40 UTC, OldRabbit736 requested changes
수고 하셨습니다,
두 가지 부분에서 변경이 필요할 것 같습니다. 해당 부분에 코멘트 남겼습니다.

2022-07-25 10:40 UTC, SteadyFlow736 commented on app/src/main/java/com/foodlab/foodReservation/store/dto/request/UpdateStoreRequest.java
>      private double longitude;
double이라는 primitive 형식에 NotNull을 걸게 되면 아무 효과가 없을 것 같습니다.
외부로부터 전달된 json을 dto로 jackson 라이브러리가 deserialization할 때, double이나 int 같은 primitive 타입의 필드를 타겟으로 하는 json 필드 자체가 없거나 값이 빈 칸("")인 경우, 해당 타입의 초기 값인 0으로 초기화 시키는 것으로 알고 있습니다. 그에따라 primitive 형식에 NotNull 같은 constraint는 아무 효과도 발휘하지 못하게 됩니다.

(시나리오 1)
json에 필드가 없거나 빈 칸인 경우를 잡으려는 목적이라면 타입을 double --> Double로 변경하는 게 맞을 것 같습니다.
이 경우에는 jackson이 해당 필드를 null로 초기화 할 것이기 때문에 NotNull 에 걸리게 됩니다.

(시나리오 2)
그러나 만약 0으로 초기화되는 것이 낫다고 판단이 될 경우, 타입을 double로 유지하고 NotNull을 제거하면 될 것 같습니다.

결과적으로 저희가 원하는 행동이 무엇인가냐에 따라 이 부분의 타입이라던가 constraint가 달라질 것 같습니다.
일단 저의 경우에는 '시나리오 1'의 경우가 맞다고 생각하여 Double로 진행하였습니다. (CreateStoreRequest DTO)

민성님의 의견은 어떠신지요?

2022-07-25 10:40 UTC, OldRabbit736 commented on app/src/main/java/com/foodlab/foodReservation/store/service/StoreService.java
> +    public StoreDetailDto getStore(Long storeId) {
소스에 StoreDetailDto 클래스 파일이 포함 안되어 있는 것 같습니다.

2022-07-25 15:15 UTC, SOULIKK commented on app/src/main/java/com/foodlab/foodReservation/store/dto/request/UpdateStoreRequest.java
>      private double longitude;
저도 1번 시나리오가 맞다고 생각합니다 좌표값 타입을 Double로 변경했습니다

2022-07-25 15:16 UTC, SOULIKK commented on app/src/main/java/com/foodlab/foodReservation/store/service/StoreService.java
> +    public StoreDetailDto getStore(Long storeId) {
누락한 dto 파일을 추가했습니다 StoreDetailDto에서 StoreDetailResponse로 이름을 수정했습니다

2022-07-26 07:25 UTC, OldRabbit736 commented
민성님, 추가로 올려주신 부분 살펴 보았습니다. 😀
제 의견은 다음과 같습니다.
1. StoreServiceTest 가 conflict 발생하는 부분이 많은데, upstream main을 한번 rebase pull 하셔서 충돌 나는 부분을 한번 해결하시고 올리시는 게 좋을 것 같습니다.
2. 메뉴 관련 기능도 이 PR에 같이 담겨 있는데, 메뉴 관련 변경점은 다른 PR로 분리하는 게 좋을 것 같습니다. 아무래도 이 PR이 Store와 관련이 있다 보니 주제를 Store로 한정시키는 게 나을 것 같습니다.

2022-07-27 08:26 UTC, OldRabbit736 commented on app/src/main/java/com/foodlab/foodReservation/item/controller/ItemController.java
> -
제 createItem을 지우신 거 같네요 ㅎㅎ;

2022-07-27 08:26 UTC, OldRabbit736 commented on app/src/main/java/com/foodlab/foodReservation/item/controller/ItemController.java
> -}
제 deleteItem을 지우셨네요 ㅠㅠ

2022-07-27 15:32 UTC, SOULIKK commented on app/src/main/java/com/foodlab/foodReservation/item/controller/ItemController.java
> -
ItemController를 다시 커밋했습니다!

2022-07-28 07:49 UTC, OldRabbit736 commented on app/src/main/java/com/foodlab/foodReservation/item/controller/ItemController.java
> -
아이고... 제가 잘못봤군요, createItem은 제가 맡은 부분이 아닌데... createStore랑 혼동했네요 죄송합니다 ㅠㅠ

2022-07-28 07:49 UTC, OldRabbit736 commented on app/src/main/java/com/foodlab/foodReservation/item/controller/ItemController.java
> -}
여기도 제가 잘못 봤네요 ㅠㅠ

2022-07-28 07:49 UTC, merged